// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: url.proto

package urlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Url_Stops int32

const (
	Url_NONSTOP Url_Stops = 0
	Url_STOP1   Url_Stops = 1
	Url_STOP2   Url_Stops = 2
)

// Enum value maps for Url_Stops.
var (
	Url_Stops_name = map[int32]string{
		0: "NONSTOP",
		1: "STOP1",
		2: "STOP2",
	}
	Url_Stops_value = map[string]int32{
		"NONSTOP": 0,
		"STOP1":   1,
		"STOP2":   2,
	}
)

func (x Url_Stops) Enum() *Url_Stops {
	p := new(Url_Stops)
	*p = x
	return p
}

func (x Url_Stops) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_Stops) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[0].Descriptor()
}

func (Url_Stops) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[0]
}

func (x Url_Stops) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_Stops.Descriptor instead.
func (Url_Stops) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 0}
}

type Url_LocationType int32

const (
	Url_UNSPECIFIED_L Url_LocationType = 0
	Url_AIRPORT       Url_LocationType = 1
	Url_CITY          Url_LocationType = 2
)

// Enum value maps for Url_LocationType.
var (
	Url_LocationType_name = map[int32]string{
		0: "UNSPECIFIED_L",
		1: "AIRPORT",
		2: "CITY",
	}
	Url_LocationType_value = map[string]int32{
		"UNSPECIFIED_L": 0,
		"AIRPORT":       1,
		"CITY":          2,
	}
)

func (x Url_LocationType) Enum() *Url_LocationType {
	p := new(Url_LocationType)
	*p = x
	return p
}

func (x Url_LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[1].Descriptor()
}

func (Url_LocationType) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[1]
}

func (x Url_LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_LocationType.Descriptor instead.
func (Url_LocationType) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 1}
}

type Url_Traveler int32

const (
	Url_UNSPECIFIED_T  Url_Traveler = 0
	Url_ADULT          Url_Traveler = 1
	Url_CHILD          Url_Traveler = 2
	Url_INFANT_ON_LAP  Url_Traveler = 3
	Url_INFANT_IN_SEAT Url_Traveler = 4
)

// Enum value maps for Url_Traveler.
var (
	Url_Traveler_name = map[int32]string{
		0: "UNSPECIFIED_T",
		1: "ADULT",
		2: "CHILD",
		3: "INFANT_ON_LAP",
		4: "INFANT_IN_SEAT",
	}
	Url_Traveler_value = map[string]int32{
		"UNSPECIFIED_T":  0,
		"ADULT":          1,
		"CHILD":          2,
		"INFANT_ON_LAP":  3,
		"INFANT_IN_SEAT": 4,
	}
)

func (x Url_Traveler) Enum() *Url_Traveler {
	p := new(Url_Traveler)
	*p = x
	return p
}

func (x Url_Traveler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_Traveler) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[2].Descriptor()
}

func (Url_Traveler) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[2]
}

func (x Url_Traveler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_Traveler.Descriptor instead.
func (Url_Traveler) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 2}
}

type Url_Class int32

const (
	Url_UNSPECIFIED_CLASS Url_Class = 0
	Url_ECONOMY           Url_Class = 1
	Url_PREMIUM_ECONOMY   Url_Class = 2
	Url_BUSINESS          Url_Class = 3
	Url_FIRST             Url_Class = 4
)

// Enum value maps for Url_Class.
var (
	Url_Class_name = map[int32]string{
		0: "UNSPECIFIED_CLASS",
		1: "ECONOMY",
		2: "PREMIUM_ECONOMY",
		3: "BUSINESS",
		4: "FIRST",
	}
	Url_Class_value = map[string]int32{
		"UNSPECIFIED_CLASS": 0,
		"ECONOMY":           1,
		"PREMIUM_ECONOMY":   2,
		"BUSINESS":          3,
		"FIRST":             4,
	}
)

func (x Url_Class) Enum() *Url_Class {
	p := new(Url_Class)
	*p = x
	return p
}

func (x Url_Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_Class) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[3].Descriptor()
}

func (Url_Class) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[3]
}

func (x Url_Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_Class.Descriptor instead.
func (Url_Class) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 3}
}

type Url_TripType int32

const (
	Url_UNSPECIFIED_TRIP Url_TripType = 0
	Url_ROUND_TRIP       Url_TripType = 1
	Url_ONE_WAY          Url_TripType = 2
)

// Enum value maps for Url_TripType.
var (
	Url_TripType_name = map[int32]string{
		0: "UNSPECIFIED_TRIP",
		1: "ROUND_TRIP",
		2: "ONE_WAY",
	}
	Url_TripType_value = map[string]int32{
		"UNSPECIFIED_TRIP": 0,
		"ROUND_TRIP":       1,
		"ONE_WAY":          2,
	}
)

func (x Url_TripType) Enum() *Url_TripType {
	p := new(Url_TripType)
	*p = x
	return p
}

func (x Url_TripType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_TripType) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[4].Descriptor()
}

func (Url_TripType) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[4]
}

func (x Url_TripType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_TripType.Descriptor instead.
func (Url_TripType) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 4}
}

type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight    []*Url_Flight  `protobuf:"bytes,3,rep,name=flight,proto3" json:"flight,omitempty"`
	Travelers []Url_Traveler `protobuf:"varint,8,rep,packed,name=travelers,proto3,enum=urlpb.Url_Traveler" json:"travelers,omitempty"`
	Class     Url_Class      `protobuf:"varint,9,opt,name=class,proto3,enum=urlpb.Url_Class" json:"class,omitempty"`
	TripType  Url_TripType   `protobuf:"varint,19,opt,name=tripType,proto3,enum=urlpb.Url_TripType" json:"tripType,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetFlight() []*Url_Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *Url) GetTravelers() []Url_Traveler {
	if x != nil {
		return x.Travelers
	}
	return nil
}

func (x *Url) GetClass() Url_Class {
	if x != nil {
		return x.Class
	}
	return Url_UNSPECIFIED_CLASS
}

func (x *Url) GetTripType() Url_TripType {
	if x != nil {
		return x.TripType
	}
	return Url_UNSPECIFIED_TRIP
}

type Url_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Url_LocationType `protobuf:"varint,1,opt,name=type,proto3,enum=urlpb.Url_LocationType" json:"type,omitempty"`
	Name string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Url_Location) Reset() {
	*x = Url_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url_Location) ProtoMessage() {}

func (x *Url_Location) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url_Location.ProtoReflect.Descriptor instead.
func (*Url_Location) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Url_Location) GetType() Url_LocationType {
	if x != nil {
		return x.Type
	}
	return Url_UNSPECIFIED_L
}

func (x *Url_Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Url_Flight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date         string          `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Stops        *Url_Stops      `protobuf:"varint,5,opt,name=stops,proto3,enum=urlpb.Url_Stops,oneof" json:"stops,omitempty"`
	SrcLocations []*Url_Location `protobuf:"bytes,13,rep,name=srcLocations,proto3" json:"srcLocations,omitempty"`
	DstLocations []*Url_Location `protobuf:"bytes,14,rep,name=dstLocations,proto3" json:"dstLocations,omitempty"`
}

func (x *Url_Flight) Reset() {
	*x = Url_Flight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url_Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url_Flight) ProtoMessage() {}

func (x *Url_Flight) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url_Flight.ProtoReflect.Descriptor instead.
func (*Url_Flight) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Url_Flight) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Url_Flight) GetStops() Url_Stops {
	if x != nil && x.Stops != nil {
		return *x.Stops
	}
	return Url_NONSTOP
}

func (x *Url_Flight) GetSrcLocations() []*Url_Location {
	if x != nil {
		return x.SrcLocations
	}
	return nil
}

func (x *Url_Flight) GetDstLocations() []*Url_Location {
	if x != nil {
		return x.DstLocations
	}
	return nil
}

var File_url_proto protoreflect.FileDescriptor

var file_url_proto_rawDesc = []byte{
	0x0a, 0x09, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x72, 0x6c,
	0x70, 0x62, 0x22, 0xad, 0x06, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x29, 0x0a, 0x06, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x72, 0x6c,
	0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x65,
	0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x75, 0x72, 0x6c, 0x70, 0x62,
	0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x65, 0x72, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x75, 0x72, 0x6c, 0x70, 0x62, 0x2e,
	0x55, 0x72, 0x6c, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x2f, 0x0a, 0x08, 0x74, 0x72, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x13, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x75, 0x72, 0x6c, 0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x54,
	0x72, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x74, 0x72, 0x69, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x1a, 0x4b, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x75, 0x72,
	0x6c, 0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0xc5,
	0x01, 0x0a, 0x06, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a,
	0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x75,
	0x72, 0x6c, 0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x48, 0x00,
	0x52, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a, 0x0c, 0x73, 0x72,
	0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x75, 0x72, 0x6c, 0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x72, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x37, 0x0a, 0x0c, 0x64, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x72, 0x6c, 0x70,
	0x62, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c,
	0x64, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x22, 0x2a, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x4e, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x54, 0x4f, 0x50, 0x31, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x4f, 0x50, 0x32,
	0x10, 0x02, 0x22, 0x38, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x5f, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x49, 0x52, 0x50, 0x4f, 0x52, 0x54,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x49, 0x54, 0x59, 0x10, 0x02, 0x22, 0x5a, 0x0a, 0x08,
	0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x65, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x5f, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x44, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x48, 0x49, 0x4c, 0x44, 0x10,
	0x02, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x46, 0x41, 0x4e, 0x54, 0x5f, 0x4f, 0x4e, 0x5f, 0x4c,
	0x41, 0x50, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x46, 0x41, 0x4e, 0x54, 0x5f, 0x49,
	0x4e, 0x5f, 0x53, 0x45, 0x41, 0x54, 0x10, 0x04, 0x22, 0x59, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x43, 0x4f, 0x4e,
	0x4f, 0x4d, 0x59, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x45, 0x4d, 0x49, 0x55, 0x4d,
	0x5f, 0x45, 0x43, 0x4f, 0x4e, 0x4f, 0x4d, 0x59, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55,
	0x53, 0x49, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x49, 0x52, 0x53,
	0x54, 0x10, 0x04, 0x22, 0x3d, 0x0a, 0x08, 0x54, 0x72, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x10, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x5f, 0x54,
	0x52, 0x49, 0x50, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x54,
	0x52, 0x49, 0x50, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x45, 0x5f, 0x57, 0x41, 0x59,
	0x10, 0x02, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x72, 0x69, 0x73, 0x75, 0x6b, 0x6f, 0x78, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2d, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x75, 0x72,
	0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_url_proto_rawDescOnce sync.Once
	file_url_proto_rawDescData = file_url_proto_rawDesc
)

func file_url_proto_rawDescGZIP() []byte {
	file_url_proto_rawDescOnce.Do(func() {
		file_url_proto_rawDescData = protoimpl.X.CompressGZIP(file_url_proto_rawDescData)
	})
	return file_url_proto_rawDescData
}

var file_url_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_url_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_url_proto_goTypes = []interface{}{
	(Url_Stops)(0),        // 0: urlpb.Url.Stops
	(Url_LocationType)(0), // 1: urlpb.Url.LocationType
	(Url_Traveler)(0),     // 2: urlpb.Url.Traveler
	(Url_Class)(0),        // 3: urlpb.Url.Class
	(Url_TripType)(0),     // 4: urlpb.Url.TripType
	(*Url)(nil),           // 5: urlpb.Url
	(*Url_Location)(nil),  // 6: urlpb.Url.Location
	(*Url_Flight)(nil),    // 7: urlpb.Url.Flight
}
var file_url_proto_depIdxs = []int32{
	7, // 0: urlpb.Url.flight:type_name -> urlpb.Url.Flight
	2, // 1: urlpb.Url.travelers:type_name -> urlpb.Url.Traveler
	3, // 2: urlpb.Url.class:type_name -> urlpb.Url.Class
	4, // 3: urlpb.Url.tripType:type_name -> urlpb.Url.TripType
	1, // 4: urlpb.Url.Location.type:type_name -> urlpb.Url.LocationType
	0, // 5: urlpb.Url.Flight.stops:type_name -> urlpb.Url.Stops
	6, // 6: urlpb.Url.Flight.srcLocations:type_name -> urlpb.Url.Location
	6, // 7: urlpb.Url.Flight.dstLocations:type_name -> urlpb.Url.Location
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_url_proto_init() }
func file_url_proto_init() {
	if File_url_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_url_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url_Flight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_url_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_url_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_url_proto_goTypes,
		DependencyIndexes: file_url_proto_depIdxs,
		EnumInfos:         file_url_proto_enumTypes,
		MessageInfos:      file_url_proto_msgTypes,
	}.Build()
	File_url_proto = out.File
	file_url_proto_rawDesc = nil
	file_url_proto_goTypes = nil
	file_url_proto_depIdxs = nil
}
